# Файл конфигурации приложения fly.toml создан для gramps-web-h6anow 15 июля 2026 г. T10:43:45Z
#
# См. https://fly.io/docs/reference/configuration/ для получения информации о том, как использовать этот файл.
#

приложение = 'gramps-web-h6anow'
первичный_регион = 'эмс'

[строить]

[окружающая среда]
  GRAMPSWEB_HOST = "0.0.0.0"
  GRAMPSWEB_PORT = "5000"
  GUNICORN_NUM_WORKERS = "1"
  
[http_service]
  внутренний_порт = 5000
  сила_https = истинный
  авто_стоп_машины = «стоп»
  машины_авто_запуска = истинный
  min_machines_running = 0
  процессы = ['приложение']

[[вм]]
  память = '1гб'
  cpu_kind = 'поделился'
  кпус = 1
  память_мб = 256
